language: node_js
node_js:
  - '4.2'
  - '5.1'
  
sudo: false  

addons:
  apt:
    packages:
    - php5-cli
    - libmcrypt4
    - libmcrypt-dev
    - libreadline-dev
    - libtidy

before_install:
  # installing latest PHP with PHPBrew
  - git clone git://github.com/php-build/php-build.git
  - cd php-build
  - PREFIX=$HOME ./install.sh 
  - ~/bin/php-build 5.4.5 ~/.php
  # installing Selenium
  - npm install selenium-standalone@latest -g
  - selenium-standalone install
  
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - "selenium-standalone start >/dev/null 2>&1 &"
  - "~/.php/bin/php -S -t test/data/app 127.0.0.1:8000 &"

script: gulp test