language: node_js
node_js:
  - '4.2'
  - '5.1'

addons:
  apt:
    packages:
    - php5-cli

before_install:
  - npm install selenium-standalone@latest -g
  - selenium-standalone install
  
before_script:
  - php -v
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - "selenium-standalone start >/dev/null 2>&1 &"
  - "php -S -t test/data/app 127.0.0.1:8000 &"

script: gulp test