language: node_js
node_js:
  - '4.2'
  - '5.1'
  
sudo: false

install:
  # installing latest PHP
  - wget http://fi2.php.net/get/php-7.0.0.tar.gz/from/a/mirror
  - tar -xzvf php-7.0.0.tar.gz
  - "cd php-7.0.0 && ./configure --prefix=$HOME/php && make && make install"    # installing Selenium
  - npm install selenium-standalone@latest -g
  - selenium-standalone install
 
before_script:
  - export PATH=$PATH:$PWD/php/bin/
  - php -v
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - "selenium-standalone start >/dev/null 2>&1 &"
  - "php -S -t test/data/app 127.0.0.1:8000 &"

script: gulp test