site_name: CodeceptJS
theme_dir: layout
pages:
- Index: 'index.md'
- Helpers:
    - 'WebDriverIO': 'helpers/WebDriverIO.md'
    - 'FileSystem': 'helpers/FileSystem.md'
copyright: Created by CodeceptJS Team